version: '3.7'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/challenge
    depends_on:
      - mongodb
    restart: on-failure
    container_name: calistuchallenge
    image: calistuchallenge:latest
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    restart: always
    container_name: mongodb
