version: '3.7'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: calistuchallenge
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
    - "8000:8000"
    volumes:
      - .:/challenge
    depends_on:
      - mongodb
    restart: on-failure
    image: calistuchallenge:lastest
  mongodb:
    image: mongo:latest
    restart: always
    ports:
    - "27017:27017"
    container_name: mongodb